### ISSUE TITLE
Method  "Post" request/api required any other configurations..? 

### ISSUE THREAD

**Issue by grajuu** [timtebeek/spring-security-samples#26]
----
Hi 
@timtebeek 

method  `"Post" ` request/api required any other configurations  In Keycloak side.?
can you add a simple post method in `/src/main/java/com/jdriven/hotels/HotelsApplication.java`
--
token exchange in from home.html 
-- Thanks in advance.

```
@SpringBootApplication
@Controller
public class HotelsApplication {

	public static void main(String[] args) {
		SpringApplication.run(HotelsApplication.class, args);
	}

	@GetMapping("/")
	public String getIndex() {
		return "index";
	}
// I changed this  to verify but didnt went smooth 
	@PostMapping("/whoami")
	@ResponseBody
	public Authentication whoami(Authentication auth) {
		return auth;
	}
```

**Comment by timtebeek** [comment]
Hi @grajuu , I'd love to help you but it's not entirely clear what you've tried or what you're asking. Could you explain your problems and what you've tried a bit more?

It seems you're working through the spring cloud gateway sample, and having issues with keycloak. Did you import the realm settings from: realm-export.json ? There are a few more instructions in:https://github.com/timtebeek/spring-security-samples/tree/master/spring-cloud-gateway-oidc-tokenrelay/keycloak

**Comment by grajuu** [comment]
Hi , 
 
@timtebeek 
am glad for quick response, 
Your Documentation is super cool. 
Yes am working with spring-cloud-gateway-oidc-tokenrelay .
I am good with  Keycloak configuration as well.
all "Get" request are working fine i.e @GetMapping("/") and @GetMapping("/whoami") from "flight microservice and hotel micrservice.

But when i tried to add a "@Postmapping(/add)" in FlightsApplication.java am getting csrf issue.

i want you to add a simple @Postmapping() example api/method in any of the "flight microservice or hotel micrservice. and consume it from Index.html or home.html.

**Comment by timtebeek** [comment]
Hi @grajuu! I've just added a small change in https://github.com/timtebeek/spring-security-samples/commit/fe38bd59ed3767c8295888613119269c262189da to serve as an example of adding a POST mapping method, along with a JUnit test for the same method.

If you run the flights sample application yourself and inspect the generated web page you'll find that Spring MVC and Thymeleaf combine to add a hidden `_csrf` field to the generated HTML form:
```
<form action="/flights/search" method="post">
  <input type="hidden" name="_csrf" value="f52a7f9a-d695-4acd-a699-f322b4b0d2d0" />
  <input name="submit" type="submit" value="Search flights" class="btn btn-primary" />
</form>
```
This hidden form field protects the form from cross-site request forgery, commonly abbreviated to csrf.

Now if you were to try to curl/httpie this endpoint, you'll find you indeed a 403 response since you're not passing a CSRF token. How best to work around this depends on your use case!

In our tests there's no need to explicitly pass a csrf token if we already use `SecurityMockMvcRequestPostProcessors.jwt()`.
